name: CI - Tests & Coverage
on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * *"

jobs:
  test:
    # Nightly runs only on main; push/PR runs on any branch
    if: github.event_name != 'schedule' || github.ref == 'refs/heads/main'
    name: Run tests & upload coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint (non-blocking)
        run: npm run lint
        continue-on-error: true

      - name: Typecheck (non-blocking)
        run: npm run typecheck
        continue-on-error: true

      - name: Run tests and generate coverage
        run: npm run coverage

      - name: Upload coverage HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage

      - name: Upload lcov to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
